name: On tags

on:
  push:
    tags:
      - '*'

jobs:
  push-docker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: teldev/melonade-discord-bot
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tag_names: true
          dockerfile: .Dockerfile
